### ISSUE TITLE
宏的自留地

### ISSUE THREAD

**Issue by YuanYiT-Hou** [BeaCox/issues-json-generator#4]
```json
{
    "title": "宏的自留地",
    "url": "https://szraz.cn/",
    "avatar": "https://cdn.afdelivr.top/npm/arcitcgn-assets-public@2022.7.24/CDN/Personal%20assets/avatar-1.jpg",
    "screenshot": "https://cdn-img.afdelivr.top/2022/08/22/6302cba963d2f.png",
    "description": "一名初中生的小破站",
    "keywords": ""
}
```

我的友链页： https://arcitcgn.cn/links.html

**Comment by YuanYiT-Hou** [comment]
really?

**Comment by BeaCox** [comment]
> really?

Please edit the first comment! You didn't follow the template!

**Comment by YuanYiT-Hou** [comment]
German National Socialist German workers' Party

**Comment by BeaCox** [comment]
> German National Socialist German workers' Party

Pull out and shoot...

**Comment by YuanYiT-Hou** [comment]
![image](https://user-images.githubusercontent.com/85769626/184600048-202e15e6-5790-41db-a190-cb813c97552b.png)
